export const API_GET_ALL_PRODUTOS = '@HOME/API_GET_ALL_PRODUTOS';
export const API_GET_ALL_CATEGORIAS = '@HOME/API_GET_ALL_CATEGORIAS';
export const API_GET_PRODUTO_BY_CATEGORIA_ID = '@HOME/API_GET_PRODUTO_BY_CATEGORIA_ID';
export const API_GET_ITENS_CARRINHO = '@HOME/API_GET_ITENS_CARRINHO';
export const API_POST_ADD_ITEM_CARRINHO = '@HOME/API_POST_ADD_ITEM_CARRINHO';
export const SET_HOME_VALUES = '@HOME/SET_HOME_VALUES';