export const API_GET_ALL_PRODUTOS = '@HOME/API_GET_ALL_PRODUTOS';
export const API_GET_ALL_CATEGORIAS = '@HOME/API_GET_ALL_CATEGORIAS';
export const API_GET_PRODUTO_BY_CATEGORIA_ID = '@HOME/API_GET_PRODUTO_BY_CATEGORIA_ID';
export const SET_HOME_VALUES = '@HOME/SET_HOME_VALUES';